services:
  greetings-app-dev:
    build: .
    image: ${DOCKERHUB_USERNAME}/python-greetings-app:latest
    container_name: greetings-app-dev
    networks:
     - greetings-app-network-compose
    ports:
     - 7001:3000
  greetings-app-stg:
    build: .
    image: ${DOCKERHUB_USERNAME}/python-greetings-app:latest
    container_name: greetings-app-stg
    networks:
     - greetings-app-network-compose
    ports:
     - 7002:3000
  greetings-app-prod:
    build: .
    image: ${DOCKERHUB_USERNAME}/python-greetings-app:latest
    container_name: greetings-app-prod
    networks:
     - greetings-app-network-compose
    ports:
     - 7003:3000

networks:
  greetings-app-network-compose:
    name: greetings-app-network-compose 